# Replace the text below to customize your site
site_name: Dhriti Dhoka - MDEF & Fab Lab Barcelona
site_description: Master in Design for Emergent Futures
site_author: Dhriti Dhoka
copyright: Copyleft 2021 "Dhriti Dhoka" - GNU Free Documentation License
repo_name: 'dhritidhoka : MDEF'
site_url: https://dhritidhoka.github.io/MDEF/
repo_url: https://github.com/dhritidhoka/MDEF.git


nav:
  - Home: index.md
  - About: about/me.md
  - Master project:
      - Initial ideas: project/project.md
  - Reflections :
      - Term 1:
          - Bootcamp: term1/01-Bootcamp.md
          - AoWS: term1/02-Atlas of Weak Signals.md
          - Bio and Agri Zero: term1/03-Bio and Agri Zero.md
          - Living With Your Own Ideas: term1/04-Living With Your Own Ideas.md
          - Tech Beyond The Myth: term1/05-Tech Beyond The Myth.md
          - Community Engagement: term1/06-Community Engagement.md
          - Extended Intelligence: term1/07-Extended Intelligence.md
          - Design Studio: term1/Design Studio.md
      - Term 2:
          - Design Studio: term2/01-Design Studio.md
          - Designing for the next billion seconds: term2/02-Designing for the next billion seconds.md
          - Remixing Materials: term2/03-Remixing Materials.md
          - Digital Prototyping for Design: term2/04-Digital Prototyping for Design.md




extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
  
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/dhritidhokaa?igshid=YmMyMTA2M2Y=
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dhritidhoka399b72188
    - icon: fontawesome/brands/github
      link: https://github.com/dhritidhoka/MDEF

theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: yellow
    accent: purple
  font:
    # See available fonts at https://fonts.google.com/
    text: Be Vietnam
    code: Cutive Mono
  icon:
    logo: material/memory
  favicon: images/favicon.svg
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
